################################################################################
# Docker compose Drupal full dev stack.
#
# A single Docker compose file that try to simply and quickly setup a full
# Drupal development environment.
#
# Project page:
#   https://github.com/Mogtofu33/docker-compose-drupal
#
# Quick set-up:
#  Copy this file, rename to docker-compose.yml, comment or remove services
#  definition based on your needs.
#  Copy and rename default.env to .env
#  Launch:
#    docker-compose up
#
# You can check your config after editing this file with:
#   docker-compose config
#
# Services settings are in config folder, check and adapt to your needs.
#
# For more information on docker compose file structure:
# @see https://docs.docker.com/compose/
#
################################################################################
version: '2'
services:
  ## Optionnal Docker ui, uncomment to enable.
  nginx:
    image: nginx:stable
#    container_name: revive2
    ports:
      - "149.56.67.70:80:80"
      - "149.56.67.70:443:443"
    links:
       - mysql
       - memcache
       - phpfpm
    volumes:
      - ${HOST_WEB_ROOT}:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/mime.types:/etc/nginx/mime.types
      - ./config/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ${HOST_LOGS_ROOT}:/var/log/nginx
    env_file: .env
    environment:
      - CONTAINER_NAME=revive2
    restart: always
  phpfpm:
    build: ./build/php7fpm
    expose:
      - "9000"
    links:
       - mysql
       - memcache
    volumes:
      - ${HOST_WEB_ROOT}:/var/www/html
      - ./config/php7:/usr/local/etc
      - ${HOST_LOGS_ROOT}:/var/log/php
    env_file: .env
    environment:
      - CONTAINER_NAME=phpfpm
    restart: always
  mysql:
    image: mariadb:latest
    expose:
      - "3306"
    volumes:
      - ${HOST_LOGS_ROOT}:/var/log/mysql
      - ${HOST_DATABASE_MYSQL}:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    env_file: .env
    environment:
      - CONTAINER_NAME=mysql
    restart: always
  memcache:
    image: memcached:alpine
    expose:
      - "11211"
    environment:
      - CONTAINER_NAME=memcache
    restart: always
