version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2-3.0.2
#    image: wodby/mariadb:10.1-3.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_INNODB_IO_CAPACITY: 20000
      MYSQL_MAX_CONNECTIONS: 1024
      MYSQL_TABLE_OPEN_CACHE: 16384
      MYSQL_SORT_BUFFER_SIZE: 16M
      MYSQL_QUERY_CACHE_TYPE: 0
      MYSQL_MAX_HEAP_TABLE_SIZE: 32M
      MYSQL_JOIN_BUFFER_SIZE: 16M
    volumes:
      - /etc/timezone:/etc/timezone
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./db:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby-php-dev
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_FPM_LOG_LEVEL: error
      PHP_FPM_PM: dynamic
      PHP_FPM_PM_MAX_CHILDREN: 1024
      PHP_FPM_PM_START_SERVERS: 12
      PHP_FPM_PM_MIN_SPARE_SERVERS: 10
      PHP_FPM_PM_MAX_SPARE_SERVERS: 100
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_DISPLAY_ERRORS: 0
      PHP_DISPLAY_STARTUP_ERRORS: 0
      PHP_ERROR_REPORTING: error
      PHP_DATE_TIMEZONE: America/Mexico_City
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
#      PHP_BLACKFIRE: 1
    volumes:
      - /etc/timezone:/etc/timezone
      - ./code:/var/www/html
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby-nginx-dev
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: error
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      NGINX_WORKER_CONNECTIONS: 4096
      NGINX_CLIENT_BODY_BUFFER_SIZE: 32k
      NGINX_CLIENT_HEADER_BUFFER_SIZE: 8k
      NGINX_KEEPALIVE_TIMEOUT: 60s
      NGINX_KEEPALIVE_REQUESTS: 256
      NGINX_GZIP_COMP_LEVEL: 5
      NGINX_FASTCGI_BUFFERS: 32 64k
      NGINX_FASTCGI_BUFFER_SIZE: 64k
      NGINX_FASTCGI_READ_TIMEOUT: 600
#      NGINX_DRUPAL_FILE_PROXY_URL: example.com
    volumes:
      - /etc/timezone:/etc/timezone
      - ./code:/var/www/html
    ports:
      - "${IP_ADDRESS}:8080:80"
      - "${IP_ADDRESS}:443:443"

  varnish:
    image: wodby-varnish-dev
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
      VARNISHD_MEMORY_SIZE: 2G
      VARNISH_BACKEND_FIRST_BYTE_TIMEOUT: 60s
      VARNISH_GRACE: 6h
#      VARNISH_EXCLUDE_URLS: "^(/update\\.php|/([a-z]{2}/)?admin|/([a-z]{2}/)?admin/.*|/([a-z]{2}/)?system/files/.*|/([a-z]{2}/)?flag/.*|.*/ajax/.*|.*/ahah/.*|.*/revive/.*)$"
    ports:
      - "${IP_ADDRESS}:80:6081"
      - "${IP_ADDRESS}:6082:6082"
    volumes:
      - /etc/timezone:/etc/timezone

#  redis:
#    image: wodby/redis:4.0-2.1.4
##    image: wodby/redis:3.2-2.1.4
#    volumes:
#      - /etc/timezone:/etc/timezone

#  adminer:
#    image: wodby/adminer:4.3-1.1.0
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:adminer.drupal.blog.gusanito.com'
#    volumes:
#      - /etc/timezone:/etc/timezone

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    ports:
#      - "${IP_ADDRESS}:8881:8881"
#    volumes:
#      - /etc/timezone:/etc/timezone

  solr:
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
    image: wodby-solr-dev
    environment:
      SOLR_HEAP: 1024m
    ports:
      - "${IP_ADDRESS}:8983:8983"
    volumes:
      - /etc/timezone:/etc/timezone

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${IP_ADDRESS}:8025:8025"
    volumes:
      - /etc/timezone:/etc/timezone

#  nodejs:
#    image: wodby/drupal-node:1.0-1.0.0
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:nodejs.drupal.blog.gusanito.com'
#    volumes:
#      - /etc/timezone:/etc/timezone
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  node:
#    image: node:alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.drupal.blog.gusanito.com'
#    expose:
#      - "3000"
#    volumes:
#      - /etc/timezone:/etc/timezone
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

  memcached:
    image: wodby/memcached:1.4-2.0.0
    volumes:
      - /etc/timezone:/etc/timezone

  memcached2:
    image: wodby/memcached:1.4-2.0.0
    volumes:
      - /etc/timezone:/etc/timezone

  memcached3:
    image: wodby/memcached:1.4-2.0.0
    volumes:
      - /etc/timezone:/etc/timezone

  memcached4:
    image: wodby/memcached:1.4-2.0.0
    volumes:
      - /etc/timezone:/etc/timezone

#  rsyslog:
#    image: wodby/rsyslog
#    volumes:
#      - /etc/timezone:/etc/timezone

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:2.10.0
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false
#    volumes:
#      - /etc/timezone:/etc/timezone

#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY
#    volumes:
#      - /etc/timezone:/etc/timezone

#  webgrind:
#    image: wodby/webgrind:1.5-1.0.0
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.drupal.blog.gusanito.com'
#    volumes:
#      - /etc/timezone:/etc/timezone
#      - files:/mnt/files


#volumes:
#  codebase:
#     target: ./code
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:
